name: Deployment Workflow

on:
  push:
    branches: [ master ]

jobs:
  deployment-job:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: SSH into the machine and run some commands
        uses: appleboy/ssh-action@master
        with:
          host: 34.222.65.59
          username: demo
          key:  ${{ secrets.SH_SSH }}
          port: 22
          script: |
            cd /home/demo/webapps/furniture-hyva
            echo "Running deployment script on the server"
            sh deployment.sh
